### PR TITLE
Refactor the Handler traits based on feedbacks on #188

### PR DESCRIPTION
**Pull request by lowlevl**
This is a PR based on the feedback received in #188, where I proposed some improvement on the overall API of the `russh` crate.

### CODE REVIEW

**Comment by ricott1** [comment]
Is there any update on this? Are you still working on it?

**Comment by lowlevl** [comment]
Hi @ricott1,

Unfortunately no, I got caught in the changes I wanted to make, rabbit-holed into making my own SSH library (which is not yet finished, https://github.com/lowlevl/assh) and forgot about this.
If you wanted to continue the work that I did, feel free !

**Comment by ricott1** [comment]
Hi @lowlevl, I tried to do the refactoring you mentioned in https://github.com/warp-tech/russh/issues/188 (the first point) in a new PR: https://github.com/warp-tech/russh/pull/247. 

If you have time would be nice if you can take a look.

**Comment by lowlevl** [comment]
Sure, but please note I don't have write privileges on this repository, so in fine it won't be me choosing if this gonna be merged :)

**Comment by Eugeny** [comment]
Closing in favour of #247

**Pull request closed without merging**
