### PR TITLE
Implement From<&str> and From<&[u8]> for CryptoVec

### PR DESCRIPTION
**Pull request by joshka**
So that `session.data(channel, "foo".into())` works.

### CODE REVIEW

**Comment by joshka** [comment]
I wanted to some simple tests for this, but wasn't sure why the test module was platform gated. Pinging @irvingoujAtDevolution for some insight on the rationale.

**Comment by irvingoujAtDevolution** [comment]
If I recall correctly, it was not there when I first created the test. `Vec<u8>` was a replacement for some libc dependent code under WASM.

**Comment by irvingoujAtDevolution** [comment]
You can safely remove it in this case, at least for these two tests.

**Comment by joshka** [comment]
> You can safely remove it in this case, at least for these two for now.

Sounds good: 5980e71..72cd436

**Comment by Eugeny** [comment]
LGTM, thanks!

@all-contributors add @joshka for code

**Pull request merged**
